sonar.projectKey=drupal11-app
sonar.projectName=drupal11-app
sonar.sources=web/modules/custom,web/themes/custom
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/vendor/**,**/node_modules/**,**/web/core/**,**/web/modules/contrib/**,**/web/themes/contrib/**,**/web/sites/default/files/**